package com.bloodbank.identity.application.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Schema(description = "Request model to verify TOTP token and enable MFA on user profile")
public class MfaEnableRequest {

    @NotBlank(message = "TOTP token code is required")
    @Pattern(regexp = "^[0-9]{6}$", message = "TOTP code must be a 6-digit numeric token")
    @Schema(example = "489123", description = "Current 6-digit token generated by authenticator app")
    private String totpCode;
}
