@echo off
echo Stopping services and removing database volumes...
docker-compose -f backend\docker-compose.yml down -v

echo Rebuilding and restarting MySQL database...
docker-compose -f backend\docker-compose.yml up -d mysql-db

echo Waiting 15 seconds for MySQL initialization...
timeout /t 15

echo Database volume reset complete! Restarting services to re-trigger Flyway migrations...
docker-compose -f backend\docker-compose.yml up -d --force-recreate
