-- V6__add_is_active_to_locations.sql
ALTER TABLE states ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE districts ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE cities ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;
